services:
  _defaults:
    autowire: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'app.command' ]

  App\:
    resource: '../src/*'

  App:
    class: \App
    public: true
    arguments:
      - !tagged_iterator app.command

  App\Service\SalaryCalculator: ~
  App\Utilities\CsvFileWriter: ~

  App\Command\ApplicationExecutionCommand:
    arguments:
      $calculator: '@App\Service\SalaryCalculator'
      $fileWriter: '@App\Utilities\CsvFileWriter'
    tags: [ 'console.command' ]
